name: Notify on New Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  notify:
    runs-on : ubuntu-latest
    steps:
      - name: Set Tag Name
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
        
      - name : Send Notification to Another Repository
        env: 
          GH_TOKEN: ${{ secrets.API_KEY }}
          TAG_NAME: ${{ env.TAG_NAME }}
        run: |
          curl -X POST -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -d '{"event_type": "api-server-tagged", "client_payload": {"tag": "'"$TAG_NAME"'"}}' \
          https://api.github.com/repos/korca0220/craftify/dispatches
